### ISSUE TITLE
With low height windows, sidebar is poorly positioned

### ISSUE THREAD

**Issue by RowiDont** [poole/hyde#103]
As you can see in the image, it seems that the sidebar content gets cut off. I'm very new to CSS, and so wasn't sure how to fix this myself. Anyone know? I had a similar problem with the sidebar's width and the title text disappearing in the window's edge, but fixed that by making the sidebar 20em instead of 18. Didn't see any similar attributes for the height though.

![hydeissue](https://cloud.githubusercontent.com/assets/9408660/9388055/7099f992-4731-11e5-9936-fd13a30192b0.PNG)

**Comment by ghost** [comment]
**Edit to explain:** The sidebar is always 100% tall with regards to the "viewport" (the actual rendering area of the browser). When the height of the content is too much to fit, it just sort of gets chopped off. A remedy would be to remove content and resize the required content until it does fit. Resizing from a width standpoint also helps, but you're also sacrificing the main content area. Below I've outlined some CSS that you could apply to try and fix that.

---

I'd play with some CSS media queries:

``` css
@media all and (max-height: 600px) {
    .sidebar { font-size: 60%; }
}
```

Something like that (tested arbitrarily in Firefox, so, it might need tweaking) could help. Also you might be able to collapse some of the sidebar features by hiding them if they're not essential. Things like the `.lead` could be set to a specific height and then using `white-space: nowrap; text-overflow: ellipsis`:

``` css
@media all and (max-height: 600px) {
    .sidebar { font-size: 60% }
    .sidebar .lead {
        height: 1em;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
}
```

After that, you could hide certain links:

``` css
@media all and (max-height: 600px) {
    .sidebar { font-size: 60% }
    .sidebar .lead {
        white-space: nowrap;
        text-overflow: ellipsis;
    }
    /* Only show if we have enough viewport height */
    .sidebar ul li.blah { display: none }
}
```
