### ISSUE TITLE
How do I make the sidebar scroll

### ISSUE THREAD

**Issue by drewcrawford** [poole/hyde#106]
Hello CSS wizards,

I have a lot of things in my sidebar and it is now off the page.

<img width="497" alt="screen shot 2015-09-07 at 8 57 48 pm" src="https://cloud.githubusercontent.com/assets/183400/9724820/242d58da-55a3-11e5-9ed5-c38a1851217f.png">

I have tried injecting `overflow: scroll` into hyde.css at various points, but I don't really know what I'm doing.

``` css
@media (min-width: 48rem) {
  .sidebar-sticky {
    position: absolute;
    right:  1rem;
    bottom: 1rem;
    left:   1rem;
    overflow: scroll; <!-- -->
  }
```

Any suggestions to put a scrollbar there?

[Site in question](http://faq.sealedabstract.com)
