### ISSUE TITLE
Colon in page title causes page not to render properly

### ISSUE THREAD

**Issue by fredrikaverpil** [poole/hyde#120]
If I use a colon in my page title, the page won't render properly:

``` yaml

---
layout: post
title: Hello: something something

---
```

Any workarounds?

**Comment by fredrikaverpil** [comment]
Ah, this seems to do the trick:

``` yaml
---
layout: post
title: 'Hello: something something'
---
```
